[[native]]
= Native
'''

In this section you will:

* Learn what GraalVM is, and what is a native build
* Build a GraalVM native image of the Quarkus application, and deploy it
* Build a GraalVM native image of the Micronaut application, and deploy it
* Build a GraalVM native image of the Spring Boot application, and deploy it

The 3 native image builds are extremely similar, so don't be surprised if there is some repetition in the instructions.

== What is GraalVM

GraalVM is a new technology, allowing to create a native build of a Java application: your application
will be compiled to a native executable, and will not need a JVM to run.
That executable will be specific
to your operation system, and will start much faster than with a JVM.

You can find more information on GraalVM at https://www.graalvm.org/[https://www.graalvm.org/].

As those builds are specific to your OS, you will be able to create a specific one on your machine, but
unless you're using Linux, that executable will not work on Docker, or in Azure Container Apps.

In order to have a native executable build on Linux, we will use again GitHub Actions.

== Installing GraalVM locally

We're going to use GraalVM Community Edition, which is free to use.

In order to use GraalVM, you will need to set it up using the instructions available at https://www.graalvm.org/22.2/docs/getting-started/#install-graalvm[https://www.graalvm.org/22.2/docs/getting-started/#install-graalvm].

As you will probably need to set up the JAVA_HOME and the PATH environment variables several times,
you can set up an alias that would make this easier, for example:

[source,shell]
----
alias graalvm="export JAVA_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java17-22.2.0/Contents/Home && export PATH=/Library/Java/JavaVirtualMachines/graalvm-ce-java17-22.2.0/Contents/Home/bin:$PATH && java -version"
----

== GitHub Actions setup

We are going to create 3 new GitHub Actions, one per native build.
As native builds are much slower than JVM builds,
this will allow us to have a faster feedback loop.

As native builds will replace the JVM builds, you need to disable the existing GitHub Action:

- In the GitHub UI, go to the `Actions` tab
- Click on the `Build and deploy Java images` workflow
- Select the `...` button, and click on `Disable workflow`

== Native build of the Quarkus application

First, let's build a local native build of the Quarkus application.

[source,shell]
----
mvn -Pnative package
----

In your `target` folder, this should create a binary called `quarkus-app-1.0.0-SNAPSHOT-runner`.
You can execute it
directly, for example:

[source,shell]
----
./target/quarkus-app-1.0.0-SNAPSHOT-runner
----

You should see the application starting very fast, and work in a similar way as the JVM build.

Now, let's create a GitHub Action that will build a native image of the Quarkus application, and deploy it.

First, create a new workflow: create a new file called `.github/workflows/deploy-quarkus-native.yml`:

[source,yaml]
----
include::{workshop-github-raw}/.github/workflows/deploy-quarkus-native.yml[]
----

[TIP]
====
Don't forget to replace the value of the `REGISTRY_URL` environment variable with the value of the `$REGISTRY_URL` variable that you copied earlier.
You use the command `echo $REGISTRY_URL` to get the value of the variable.
====

You can now `git push` your changes, and this new workflow should build a native image, and deploy it instead
of the JVM image.

== Native build of the Micronaut application

Let's build a local native build of the Micronaut application.

[source,shell]
----
mvn package -Dpackaging=native-image
----

In your `target` folder, this should create a binary called `./target/micronaut-app`.
You can execute it
directly, for example:

[source,shell]
----
./target/./target/micronaut-app
----

You should see the application starting very fast, and work in a similar way as the JVM build.

Now, let's create a GitHub Action that will build a native image of the Micronaut application, and deploy it.

First, create a new workflow: create a new file called `.github/workflows/deploy-micronaut-native.yml`:

[source,yaml]
----
include::{workshop-github-raw}/.github/workflows/deploy-micronaut-native.yml[]
----

[TIP]
====
Don't forget to replace the value of the `REGISTRY_URL` environment variable with the value of the `$REGISTRY_URL` variable that you copied earlier.
You use the command `echo $REGISTRY_URL` to get the value of the variable.
====

You can now `git push` your changes, and this new workflow should build a native image, and deploy it instead
of the JVM image.

== Native build of the Spring Boot application

Let's build a local native build of the Spring Boot application.

[source,shell]
----
mvn -Pnative package
----

In your `target` folder, this should create a binary called `springboot-app`.
You can execute it
directly, for example:

[source,shell]
----
./target/springboot-app
----

You should see the application starting very fast, and work in a similar way as the JVM build.

Now, let's create a GitHub Action that will build a native image of the Spring Boot application, and deploy it.

First, create a new workflow: create a new file called `.github/workflows/deploy-springboot-native.yml`:

[source,yaml]
----
include::{workshop-github-raw}/.github/workflows/deploy-springboot-native.yml[]
----

[TIP]
====
Don't forget to replace the value of the `REGISTRY_URL` environment variable with the value of the `$REGISTRY_URL` variable that you copied earlier.
You use the command `echo $REGISTRY_URL` to get the value of the variable.
====

You can now `git push` your changes, and this new workflow should build a native image, and deploy it instead
of the JVM image.
