[[welcome]]
= Welcome
Let's start from the beginning.
Quarkus.
What's Quarkus?
That's a pretty good question and probably a good start.
If you go to the https://quarkus.io[Quarkus web site], you'll read that Quarkus is "_A Kubernetes Native Java stack tailored for OpenJDK HotSpot & GraalVM, crafted from the best of breed Java libraries and standards_."
This description is somewhat unclear but does an outstanding job at using bankable keywords.
It's also written: "_Supersonic Subatomic Java_."
Still very foggy.
In practice, Quarkus is a stack to develop distributed systems and modern applications in Java, Kotlin, or Scala.
Quarkus applications are tailored for the Cloud, containers, and Kubernetes.
That does not mean you can't use Quarkus in other environments, there are no limits, but the principles infused in Quarkus have made containerization of applications more efficient.
In this workshop, we will explain what Quarkus is and because the best way to understand Quarkus is to use it, build a set of microservices with it.
Again, Quarkus is not limited to microservices, but it's a generally well-understood type of architecture.

This workshop offers attendees an intro-level, hands-on session with Quarkus, from the first line of code to making services, to consuming them, and finally to assembling everything in a consistent system.
But, what are we going to build?
Well, it's going to be a set of microservices:

* Using Quarkus
* Using HTTP and events (with Apache Kafka)
* With some parts of the dark side of microservices (resilience, health, monitoring with Prometheus)
* Answer the ultimate question: are super-heroes stronger than super-villains?

This workshop is a BYOL (_Bring Your Own Laptop_) session, so bring your Windows, OSX, or Linux laptop.
You need JDK {jdk-version} on your machine, Apache Maven ({maven-version}), and Docker.
On Mac and Windows, Docker for _x_ is recommended instead of the Docker toolbox setup.

What you are going to learn:

* What is Quarkus, and how you can use it
* How to build an HTTP endpoint (REST API) with Quarkus
* How to access a relational database
* How you can use Swagger and OpenAPI
* How you test your microservice
* How to build a reactive microservice, including reactive data access
* How you improve the resilience of your service
* How to build event-driven microservices with Kafka
* How to build native executable
* How to extend Quarkus with extensions
* And much more!

Ready? Here we go!

== Presenting the Workshop

=== What Is This Workshop About?

=== What Will You Be Developing?

[plantuml,align=center,format=png]
----
include::{plantDir}/welcome-physical-architecture.puml[]
----

=== What Will You Be Deploying?

=== How Does This Workshop Work?

You have this material in your hands, and you can now follow it step by step. The structure of this workshop is as follow :

1. _Installing all the needed tools_: in this section, you will install all the tools and code to be able to bundle, package and deploy our application.

2. _Setup Azure resources_: this section introduces Azure and the Container Apps service to prepare all the needed resources for our application. You will create an entire infrastructure on Azure (Container Registry, Postgres databases, etc.) to make everything ready for deployment.

3. _Running the Application Locally_: in this section, you will build Docker images out of our microservices, execute them locally with Docker compose, push them to Azure Registry, all that using Docker and Azure CLI.

4. _Setup CI/CD and deploy application_: in this section, you will setup a CI/CD pipeline using GitHub Actions so that our application builds and deploy automatically on new commits.

5. _Administrating_: in this section, you will add some load to your microservices, monitor them, scale them, check the logs, etc.

=== What Do You Have to Do?

This workshop should be as self-explanatory as possible. So your job is to follow the instructions by yourself, do what you are supposed to do, and do not hesitate to ask for any clarification or assistance; that's why the team is here.

Oh, and be ready to have some fun!

=== Pre-requisites

[cols="1,1"]
|===
| Java                | {jdk-version} https://docs.microsoft.com/java/openjdk/download?WT.mc_id=javascript-0000-yolasors[Get OpenJDK]
| Maven               | {maven-version} https://maven.apache.org/download.cgi[Get Maven]
| Docker              | {docker-version} https://docs.docker.com/get-docker/[Get Docker]
| Azure CLI           | https://learn.microsoft.com/cli/azure/install-azure-cli?WT.mc_id=javascript-0000-yolasors#install[Get Azure CLI]
| Git                 | https://git-scm.com
| GitHub account      | https://github.com/join
| Azure account       | https://azure.microsoft.com/free/?WT.mc_id=javascript-0000-yolasors[https://azure.microsoft.com/free]

If you're attending this workshop at Devoxx BE, you can use this link to redeem an Azure Pass: https://azcheck.in/dbe221010.
Once you have your code, copy it and click on the button *Get on board with Azure*, then follow the instructions.

| A code editor, such as VS Code, Eclipse, or IntelliJ | https://code.visualstudio.com/Download?WT.mc_id=javascript-0000-yolasors[Get VS Code]

|===

If you have VS Code and Docker installed on your machine, the quickest way to set up your environment is to use the pre-configured https://code.visualstudio.com/docs/remote/containers?WT.mc_id=javascript-0000-yolasors[dev container] of the template project. Install the https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack&WT.mc_id=javascript-0000-yolasors[Remote Development extension] in VS Code, and skip to the next section.

TIP: You can learn more about dev containers in https://docs.microsoft.com/shows/beginners-series-to-dev-containers/?WT.mc_id=javascript-0000-yolasors[this video series].

You can test your installation by running the following commands:

[source,shell]
----
java -version
mvn --version
docker --version
az --version
----
