[[quarkus]]
= Quarkus

'''

In this section you will:

* Develop a REST API with Quarkus that consumes memory and CPU
* Add a Statistics persistent entity to store metrics in a Postgres database
* Configure the application
* Develop some tests to validate the behavior of the application
* Test the application locally
* Run the application locally
* Check a few metrics locally

When you created your repository from the GitHub template, you should have a directory called `quarkus-app` in your current directory.
This is the root of the Quarkus microservice source code that we will be using in this section.

== The Quarkus REST Resource

The Quarkus application is made of a simple REST resource that consumes memory and CPU.
The resource is defined in the `QuarkusResource` class.
Create a new file called `QuarkusResource.java` under the `src/main/java/io/containerapps/javaruntime/workshop/quarkus` package.
Then, add the following to the header of the class.
As you can see, it is a JAX-RS resource that is exposed on the `/quarkus` path.

[[quarkus-listing-rest-resource-1]]
.Header of the Quarkus REST Resource
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResource.java[tag=adocHeader]
}
----

Let's add a `hello` method returning _Hello World_ so we can quickly check if our endpoint responds or not.

[[quarkus-listing-rest-resource-2]]
.Hello Method
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResource.java[tag=adocMethodHello]
----

Let's now add a `cpu` method that consumes CPU depending on a few optional parameters.

* `iterations` the more iterations you have, the more CPU it consumes.
* `db` if this parameter is set to true, the statistics are stored in the database.
That allows us to check the impact of the database on the CPU consumption.
* `desc` any optional description you want to persist in the database

[[quarkus-listing-rest-resource-3]]
.CPU Method
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResource.java[tag=adocMethodCPU]
----

Now, add a `memory` method that consumes memory depending on a few optional parameters.

* `bites` the more bits you have, the more memory it consumes.
* `db` if this parameter is set to true, the statistics are stored in the database.
* `desc` any optional description you want to persist in the database

[[quarkus-listing-rest-resource-4]]
.Memory Method
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResource.java[tag=adocMethodMemory]
----

Let's also create a method to retrieve the statistics from the database.
This is very easy to do with https://quarkus.io/guides/hibernate-orm-panache[Panache].

[[quarkus-listing-rest-resource-5]]
.Method Returning all the Statistics
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResource.java[tag=adocMethodStats]
----

At this stage, the code does not compile yet, because there are a few missing classes.
Let's create them now.

== Transactions and ORM

When the database is enabled, the statistics are stored in the database.
For that we need a `Statistics` entity with a few enumerations that will be mapped to the Postgres database.
Create the `Statistics` entity in the `src/main/java/io/containerapps/javaruntime/workshop/quarkus` package.

[[quarkus-listing-entity]]
.Statistics Entity
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/java/io/containerapps/javaruntime/workshop/quarkus/Statistics.java[]
----

For manipulating the entity, we need a repository.
Create the `StatisticsRepository` class under the same package.
Notice that `StatisticsRepository` is a https://quarkus.io/guides/hibernate-orm-panache[Panache Repository] that extends the `PanacheRepository` class.

[[quarkus-listing-repository]]
.Statistics Repository
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/java/io/containerapps/javaruntime/workshop/quarkus/StatisticsRepository.java[]
----

== Compiling the Application

You should have all the code to compile the application.
To make sure you have all the code and dependencies, run the following command:

[source,shell]
----
mvn compile
----

== Configuring the Application

There is not much to configure as Quarkus is configured by default to use the Postgres database (thanks to https://quarkus.io/guides/dev-services[DevService]).
To make sure our 3 microservices can run side by side, we need to configure the listening port of the Quarkus application.
To have this service exposed on the port 8701, add the following configuration in the `src/main/resources/application.properties` file.

[[quarkus-listing-config]]
.Configuration Properties
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/resources/application.properties[tags=adocProperties]
----

== Testing the Application Locally

Now, to make sure that the application works as expected, we need to write some tests.
For that, we will use https://quarkus.io/guides/getting-started-testing[Quarkus Test Framework] that is based on https://junit.org/junit5/[JUnit 5] and use https://github.com/rest-assured/rest-assured[RESTAssured].
Behind the scene, Quarkus uses https://www.testcontainers.org[TestContainers] with its https://quarkus.io/guides/dev-services[DevServices] feature.
That's why we need Docker to run the tests and run the application.

Create the `QuarkusResourceTest` class under the `src/test/java/io/containerapps/javaruntime/workshop/quarkus` package.
Then, add the following to the header of the class.

[[quarkus-listing-test-1]]
.Header of the Test Class
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/test/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResourceTest.java[tag=adocHeader]
}
----

First, let's write a test to check that the `hello` method returns the right _Hello World_ string.

[[quarkus-listing-test-2]]
.Testing the Hello Endpoint
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/test/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResourceTest.java[tag=adocTestHello]
----

Then, we write another test to check that the `cpu` method consumes CPU and takes the right parameters.

[[quarkus-listing-test-3]]
.Testing the CPU Endpoint
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/test/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResourceTest.java[tag=adocTestCPU]
----

And we do the same for the `memory` method.

[[quarkus-listing-test-4]]
.Testing the Memory Endpoint
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/test/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResourceTest.java[tag=adocTestMemory]
----

Let's also create a simple test to make sure the statistics are stored in the database.

[[quarkus-listing-test-5]]
.Testing Retrieving the Statistics from the Database
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/test/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResourceTest.java[tag=adocTestStats]
----

Now that you have your tests methods, make sure you have *Docker Desktop up and running* (as it needs to start a Postgres database) and run them with the following command (the first Quarkus test can take a while as TestContainers needs to download the Postgres image):

[source,shell]
----
mvn test
----

All the tests should pass and you should see the following output:

[source,shell]
----
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
----

== Running the Application Locally

Now that the tests are all green, let's execute the application locally and execute a few `curl` commands.
Make sure you still have Docker up and running and execute the following command under the `quarkus-app` directory:

[source,shell]
----
mvn quarkus:dev
----

In another terminal you can execute the following `curl` commands to invoke the endpoint:

[source,shell]
----
curl 'localhost:8701/quarkus'

curl 'localhost:8701/quarkus/cpu?iterations=10&db=true&desc=java17'

curl 'localhost:8701/quarkus/memory?bites=10&db=true&desc=java17'
----

You can change the parameters to see how the application behaves.
Change the number of iterations and the number of bites to see how the performance is impacted (with and without database).

[source,shell]
----
curl 'localhost:8701/quarkus/cpu?iterations=50'
curl 'localhost:8701/quarkus/cpu?iterations=100'
curl 'localhost:8701/quarkus/cpu?iterations=100&db=true'

curl 'localhost:8701/quarkus/memory?bites=50'
curl 'localhost:8701/quarkus/memory?bites=100'
curl 'localhost:8701/quarkus/memory?bites=100&db=true'
----

You can check the content of the database with:

[source,shell]
----
curl 'localhost:8701/quarkus/stats'

# or if you have "jq" installed you can make it prettier with
# curl 'localhost:8701/quarkus/stats' | jq
----

That's it for the Quarkus application.
Now, let's move to the Micronaut application.
