[[quarkus]]
= Quarkus

'''

We need to expose a REST API allowing CRUD operations on villains.
This microservice is, let's say, a _classical_ REST microservice.
It uses HTTP to expose a REST API and internally store data into a database.
It's using the _imperative_ development model.

In the following section you will:

* xxxx
* xxxx
* xxxx
* xxxx
* xxxx
* xxxx

IMPORTANT: This service is exposed on the port 8701.

But first, let's describe our service.
The Super-Villains microservice manages villains with their names, powers, and so on.
The REST API allows adding, removing, listing, and picking a random villain from the stored set.
Nothing outstanding but a good first step to discover Quarkus.

== The Quarkus REST Resource

[[quarkus-listing-rest-resource-1]]
.Header of the Quarkus REST Resource
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResource.java[tag=adocHeader]
----

[[quarkus-listing-rest-resource-2]]
.Hello Method
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResource.java[tag=adocMethodHello]
----

[[quarkus-listing-rest-resource-3]]
.CPU Method
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResource.java[tag=adocMethodCPU]
----

[[quarkus-listing-rest-resource-4]]
.Memory Method
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResource.java[tag=adocMethodMemory]
----

== Transactions and ORM

[[quarkus-listing-entity]]
.Statistics Entity
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/java/io/containerapps/javaruntime/workshop/quarkus/Statistics.java[]
----

[[quarkus-listing-repository]]
.Statistics Repository
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/java/io/containerapps/javaruntime/workshop/quarkus/StatisticsRepository.java[]
----

== Testing the Application

== Running the Application

== Deploying the Application
