[[quarkus]]
= Quarkus

'''

In this section you will:

* Develop a REST API with Quarkus that consumes memory and CPU
* Add a Statistics persistent entity to store metrics in a Postgres database
* Configure the application
* Develop some tests to validate the behavior of the application
* Test the application locally
* Run the application locally
* Check a few metrics locally

== The Quarkus REST Resource

The Quarkus application is a simple REST resource that exposes a single endpoint to consume memory and CPU.
The resource is defined in the `src/main/java/org/acme/quarkus/sample/QuarkusResource.java` file:
As you can see in the header of the class, it is a JAX-RS resource that is exposed on the `/quarkus` path.

[[quarkus-listing-rest-resource-1]]
.Header of the Quarkus REST Resource
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResource.java[tag=adocHeader]
----

The resource exposes a `hello` method returning _Hello World_ so we can quickly check if our endpoint responds or not.

[[quarkus-listing-rest-resource-2]]
.Hello Method
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResource.java[tag=adocMethodHello]
----

The `cpu` method consumes CPU depending on a few optional parameters.

* `iterations` the more iterations you have, the more CPU it consumes.
* `db` if this parameter is set to true, the statistics are stored in the database. That allows us to check the impact of the database on the CPU consumption.
* `desc` any optional description you want to persist in the database

[[quarkus-listing-rest-resource-3]]
.CPU Method
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResource.java[tag=adocMethodCPU]
----

The `memory` method consumes memory depending on a few optional parameters.

* `bites` the more bits you have, the more memory it consumes.
* `db` if this parameter is set to true, the statistics are stored in the database.
* `desc` any optional description you want to persist in the database

[[quarkus-listing-rest-resource-4]]
.Memory Method
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResource.java[tag=adocMethodMemory]
----

== Transactions and ORM

When the database is enabled, the statistics are stored in the database.
For that we need a `Statistics` entity with a few enumerations.

[[quarkus-listing-entity]]
.Statistics Entity
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/java/io/containerapps/javaruntime/workshop/quarkus/Statistics.java[]
----

For manipulating the entity, we need a repository
Notice that `StatisticsRepository` is a https://quarkus.io/guides/hibernate-orm-panache[Panache Repository] that extends the `PanacheRepository` class.

[[quarkus-listing-repository]]
.Statistics Repository
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/java/io/containerapps/javaruntime/workshop/quarkus/StatisticsRepository.java[]
----

== Configuring the Application

There is not much to configure as Quarkus is configured by default to use the Postgres database (thanks to https://quarkus.io/guides/dev-services[DevService]).
This service is exposed on the port 8701.

[[quarkus-listing-config]]
.Configuration Properties
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/main/resources/application.properties[]
----

== Testing the Application Locally

Now, to make sure that the application works as expected, we need to write some tests.
For that, we will use https://quarkus.io/guides/getting-started-testing[Quarkus Test Framework] that is based on https://junit.org/junit5/[JUnit 5] and use https://github.com/rest-assured/rest-assured[RESTAssured].

[[quarkus-listing-test-1]]
.Header of the Test Class
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/test/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResourceTest.java[tag=adocHeader]
----

First, let's write a test to check that the `hello` method returns the right _Hello World_ string.

[[quarkus-listing-test-2]]
.Testing the Hello Endpoint
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/test/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResourceTest.java[tag=adocTestHello]
----

Then, we right another test to check that the `cpu` method consumes CPU and takes the right parameters.

[[quarkus-listing-test-3]]
.Testing the CPU Endpoint
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/test/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResourceTest.java[tag=adocTestCPU]
----

And we do the same for the `memory` method.

[[quarkus-listing-test-4]]
.Testing the Memory Endpoint
[source,indent=0]
----
include::{workshop-github-raw}/quarkus-app/src/test/java/io/containerapps/javaruntime/workshop/quarkus/QuarkusResourceTest.java[tag=adocTestMemory]
----

Now that you have your tests, make sure you have Docker Desktop up and running (as it needs to start a Postgres database) and run them with the following command:

[source,shell]
----
mvn test
----

== Running the Application Locally

Now that the tests are all green, let's execute the application locally and execute a few `curl` commands.
Make sure you still have Docker up and running and execute:

[source,shell]
----
mvn quarkus:dev
----

In another terminal you can execute the following `curl` commands to invoke the endpoint:

[source,shell]
----
curl 'localhost:8701/quarkus'

curl 'localhost:8701/quarkus/cpu?iterations=10&db=true&desc=java17'

curl 'localhost:8701/quarkus/memory?bites=10&db=true&desc=java17'
----

