[[springboot]]
= Developing the Spring Boot Application

In this section you will:

* Develop a REST API with Spring Boot that consumes memory and CPU (the exact same algorithm than before)
* Add a Statistics persistent entity to store metrics in a PostgreSQL database
* Configure the application
* Develop some tests to validate the behavior of the application
* Test the application locally
* Run the application locally
* Check a few metrics locally

In your repository you should have a directory called `springboot-app` .
This is the root of the Spring Boot microservice source code that we will be using in this section.

== The Spring Boot REST Resource

The Spring Boot application is a simple REST resource that exposes a single endpoint to consume memory and CPU.
Before creating the REST resource, let's check the existing main Spring Boot class that will bootstrap the application.
Check the following code in the `SpringbootApplication` class under the `io/containerapps/javaruntime/workshop/springboot` package.

[[springboot-listing-rest-resource]]
.Bootstrapping Spring Boot Class
[source,indent=0]
----
include::{workshop-github-raw}/springboot-app/src/main/java/io/containerapps/javaruntime/workshop/springboot/SpringbootApplication.java[]
----

The REST resource is defined in the `src/main/java/io/containerapps/javaruntime/workshop/springboot/SpringbootResource.java` file.
Create this new `SpringbootResource` class under the `io.containerapps.javaruntime.workshop.springboot` package.
As you can see in the header of the class, the resource is exposed on the `/springboot` path.

[[springboot-listing-rest-resource-1]]
.Header of the Spring Boot REST Resource
[source,indent=0]
----
include::{workshop-github-raw}/springboot-app/src/main/java/io/containerapps/javaruntime/workshop/springboot/SpringbootResource.java[tag=adocHeader]
}
----

Let's add a `hello` method returning _Hello World_ so we can quickly check if our endpoint responds or not.

[[springboot-listing-rest-resource-2]]
.Hello Method
[source,indent=0]
----
include::{workshop-github-raw}/springboot-app/src/main/java/io/containerapps/javaruntime/workshop/springboot/SpringbootResource.java[tag=adocMethodHello]
----

Let's now add a `cpu` method that consumes CPU depending on a few optional parameters.

* `iterations` the more iterations you have, the more CPU it consumes.
* `db` if this parameter is set to true, the statistics are stored in the database.
That allows us to check the impact of the database on the CPU consumption.
* `desc` any optional description you want to persist in the database

[[springboot-listing-rest-resource-3]]
.CPU Method
[source,indent=0]
----
include::{workshop-github-raw}/springboot-app/src/main/java/io/containerapps/javaruntime/workshop/springboot/SpringbootResource.java[tag=adocMethodCPU]
----

Now, add a `memory` method that consumes memory depending on a few optional parameters.

* `bites` the more bits you have, the more memory it consumes.
* `db` if this parameter is set to true, the statistics are stored in the database.
* `desc` any optional description you want to persist in the database

[[springboot-listing-rest-resource-4]]
.Memory Method
[source,indent=0]
----
include::{workshop-github-raw}/springboot-app/src/main/java/io/containerapps/javaruntime/workshop/springboot/SpringbootResource.java[tag=adocMethodMemory]
----

Let's also create a method to retrieve the statistics from the database.

[[springboot-listing-rest-resource-5]]
.Method Returning all the Statistics
[source,indent=0]
----
include::{workshop-github-raw}/springboot-app/src/main/java/io/containerapps/javaruntime/workshop/springboot/SpringbootResource.java[tag=adocMethodStats]
----

At this stage, the code does not compile yet, because there are a few missing classes.
Let's create them now.

== Transactions and ORM

When the database is enabled, the statistics are stored in the database.
For that we need a `Statistics` entity with a few enumerations.
Create the `Statistics` entity in the `src/main/java/io/containerapps/javaruntime/workshop/springboot` directory.

[[springboot-listing-entity]]
.Statistics Entity
[source,indent=0]
----
include::{workshop-github-raw}/springboot-app/src/main/java/io/containerapps/javaruntime/workshop/springboot/Statistics.java[]
----

For manipulating the entity, we need a repository.
Create the `StatisticsRepository` class under the same package.

[[springboot-listing-repository]]
.Statistics Repository
[source,indent=0]
----
include::{workshop-github-raw}/springboot-app/src/main/java/io/containerapps/javaruntime/workshop/springboot/StatisticsRepository.java[]
----

== Compiling the Spring Boot Application

You should have all the code to compile the application.
To make sure you have all the code and dependencies, run the following command:

[source,shell]
----
mvn compile
----

== Configuring the Spring Boot Application

We need to configure the default PostgreSQL database and Hibernate ORM.
This service is exposed on the port 8703.
Add the following to the `src/main/resources/application.properties` file.

[[springboot-listing-config]]
.Configuration Properties
[source,indent=0]
----
include::{workshop-github-raw}/springboot-app/src/main/resources/application.properties[]
----

== Testing the Spring Boot Application Locally

Now, to make sure that the application works as expected, we need to write some tests.
Remember that the tests need a PostgreSQL database to run.
For that, we need to configure Testcontainers.
Open up the `SpringbootApplicationTests` class under the `src/test/java/io/containerapps/javaruntime/workshop/springboot` folder, and add Testcontainers support in it:

[[springboot-listing-test]]
.Test Class Configuring Testcontainers
[source,indent=0]
----
include::{workshop-github-raw}/springboot-app/src/test/java/io/containerapps/javaruntime/workshop/springboot/SpringbootApplicationTests.java[]
----

Then, all our tests go into the `SpringbootResourceTest` class.
Create the `SpringbootResourceTest` class under the same package that `SpringbootApplicationTests`.

[[springboot-listing-test-1]]
.Header of the Test Class
[source,indent=0]
----
include::{workshop-github-raw}/springboot-app/src/test/java/io/containerapps/javaruntime/workshop/springboot/SpringbootResourceTest.java[tag=adocHeader]
}
----

First, let's write a test to check that the `hello` method returns the right _Hello World_ string.

[[springboot-listing-test-2]]
.Testing the Hello Endpoint
[source,indent=0]
----
include::{workshop-github-raw}/springboot-app/src/test/java/io/containerapps/javaruntime/workshop/springboot/SpringbootResourceTest.java[tag=adocTestHello]
----

Then, we write another test to check that the `cpu` method consumes CPU and takes the right parameters.

[[springboot-listing-test-3]]
.Testing the CPU Endpoint
[source,indent=0]
----
include::{workshop-github-raw}/springboot-app/src/test/java/io/containerapps/javaruntime/workshop/springboot/SpringbootResourceTest.java[tag=adocTestCPU]
----

And we do the same for the `memory` method.

[[springboot-listing-test-4]]
.Testing the Memory Endpoint
[source,indent=0]
----
include::{workshop-github-raw}/springboot-app/src/test/java/io/containerapps/javaruntime/workshop/springboot/SpringbootResourceTest.java[tag=adocTestMemory]
----

Let's also create a simple test to make sure the statistics are stored in the database.

[[springboot-listing-test-5]]
.Testing Retrieving the Statistics from the Database
[source,indent=0]
----
include::{workshop-github-raw}/springboot-app/src/test/java/io/containerapps/javaruntime/workshop/springboot/SpringbootResourceTest.java[tag=adocTestStats]
----

Now that you have your tests methods, make sure you have Docker Desktop up and running (as it needs to start a PostgreSQL database) and run them with the following command:

[source,shell]
----
mvn test
----

All the tests should pass and you should see the following output:

[source,shell]
----
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
----

== Running the Spring Boot Application Locally

Now that the tests are all green, let's execute the application locally and execute a few `curl` commands.
To run the application, we first need to have our PostgreSQL database up and running.
Make sure you still have Docker up and running and execute under the `infrastructure` directory:

[source,shell]
----
docker compose -f postgres.yaml up
----

Under the `springboot-app` directory, execute the following command:

[source,shell]
----
mvn spring-boot:run
----

In another terminal you can execute the following `curl` commands to invoke the endpoint:

[source,shell]
----
curl 'localhost:8703/springboot'

curl 'localhost:8703/springboot/cpu?iterations=10&db=true&desc=java17'

curl 'localhost:8703/springboot/memory?bites=10&db=true&desc=java17'
----

You can change the parameters to see how the application behaves.
Change the number of iterations and the number of bites to see how the performance is impacted (with and without database).

[source,shell]
----
curl 'localhost:8703/springboot/cpu?iterations=50'
curl 'localhost:8703/springboot/cpu?iterations=100'
curl 'localhost:8703/springboot/cpu?iterations=100&db=true'

curl 'localhost:8703/springboot/memory?bites=50'
curl 'localhost:8703/springboot/memory?bites=100'
curl 'localhost:8703/springboot/memory?bites=100&db=true'
----

You can check the content of the database with:

[source,shell]
----
curl 'localhost:8703/springboot/stats'

# or if you have "jq" installed you can make it prettier with
# curl 'localhost:8703/springboot/stats' | jq
----

That's it.
We now have developed and tested locally our three microservices.
Time to containerize them and deploy them to Azure Container Apps.
