FROM --platform=linux/amd64 eclipse-temurin:19-jre-alpine
RUN addgroup -S micronaut && adduser -S micronaut -G micronaut
USER micronaut:micronaut
COPY target/micronaut-app-*.jar micronaut-app.jar
CMD java -Dcom.sun.management.jmxremote ${JAVA_OPTS} -jar micronaut-app.jar
EXPOSE 8702
