== Setting Up Your Development Environment Manually

If you decide to setup your environment yourself, you will need to install the following tools:

[cols="1,1"]
|===
| Java {jdk-version}       | https://learn.microsoft.com/java/openjdk/download[Get OpenJDK]
| Maven {maven-version}    | https://maven.apache.org/download.cgi[Get Maven]
| Docker {docker-version}  | https://docs.docker.com/get-docker[Get Docker]
| Azure CLI                | https://learn.microsoft.com/cli/azure/install-azure-cli#install[Get Azure CLI]
| Git                      | https://git-scm.com
| GitHub account           | https://github.com/join
| Azure account            | https://azure.microsoft.com/free[Get a free Azure account]
| A code editor, such as VS Code, Eclipse, or IntelliJ | https://code.visualstudio.com/Download[Get VS Code]
| cURL (or any other HTTP client) | https://curl.se/download.html[Get cURL]
| GraalVM (optional)       | https://www.graalvm.org/downloads[Get GraalVM]
| jq (optional)            | https://stedolan.github.io/jq/download[Get jq]
|===

You can test your installation by running the following commands:

[source,shell]
----
java -version
mvn --version
docker --version
az --version
git --version
curl --version
jq --version
----

If everything is installed correctly, you should see the version of each tool.

[WARNING]
====
If you are on Windows, you will need to run *bash* commands.
You have multiples way to do that:

* Use the *Git Bash* command line that comes with Git. Open the start menu, and search for "Git Bash".
* Install the *Windows Subsystem for Linux* (WSL) with a Linux distribution (eg. Ubuntu).
You can follow the instructions https://learn.microsoft.com/en-us/windows/wsl/install[here].
* Use *Visual Studio Code* with the Dev Containers setup (see below).
====

