FROM ghcr.io/graalvm/native-image:22.2.0
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/springboot-app /work/application

EXPOSE 8703
USER 1001

CMD ["./application"]
