[[micronaut]]
= Micronaut

'''

In this section you will:

* Develop a REST API with Micronaut that consumes memory and CPU (the exact same algorithm than before)
* Add a Statistics persistent entity to store metrics in a Postgres database
* Configure the application
* Develop some tests to validate the behavior of the application
* Test the application locally
* Run the application locally
* Check a few metrics locally

In your repository you should have another directory called `micronaut-app` .
This is the root of the Micronaut microservice source code that we will be using in this section.

== The Micronaut REST Resource

The Micronaut application is also made of a simple REST resource that exposes the endpoints that consume memory and CPU.
Before creating the REST resource, we need to create a main Micronaut class that will bootstrap the application.
Create the `MicronautApplication` under the `io/containerapps/javaruntime/workshop/micronaut` package.

[[micronaut-listing-rest-resource]]
.Bootstrapping Micronaut Class
[source,indent=0]
----
include::{workshop-github-raw}/micronaut-app/src/main/java/io/containerapps/javaruntime/workshop/micronaut/MicronautApplication.java[]
----

The REST resource is defined in the `MicronautResource` class.
Create a new file called `MicronautResource.java` under the `src/main/java/io/containerapps/javaruntime/workshop/micronaut` directory.
As you can see in the header of the class, the resource is exposed on the `/micronaut` path.

[[micronaut-listing-rest-resource-1]]
.Header of the Micronaut REST Resource
[source,indent=0]
----
include::{workshop-github-raw}/micronaut-app/src/main/java/io/containerapps/javaruntime/workshop/micronaut/MicronautResource.java[tag=adocHeader]
----

Let's add a `hello` method returning _Hello World_ so we can quickly check if our endpoint responds or not.

[[micronaut-listing-rest-resource-2]]
.Hello Method
[source,indent=0]
----
include::{workshop-github-raw}/micronaut-app/src/main/java/io/containerapps/javaruntime/workshop/micronaut/MicronautResource.java[tag=adocMethodHello]
----

Let's now add a `cpu` method that consumes CPU depending on a few optional parameters.

* `iterations` the more iterations you have, the more CPU it consumes.
* `db` if this parameter is set to true, the statistics are stored in the database. That allows us to check the impact of the database on the CPU consumption.
* `desc` any optional description you want to persist in the database

[[micronaut-listing-rest-resource-3]]
.CPU Method
[source,indent=0]
----
include::{workshop-github-raw}/micronaut-app/src/main/java/io/containerapps/javaruntime/workshop/micronaut/MicronautResource.java[tag=adocMethodCPU]
----

Now, add a `memory` method that consumes memory depending on a few optional parameters.

* `bites` the more bits you have, the more memory it consumes.
* `db` if this parameter is set to true, the statistics are stored in the database.
* `desc` any optional description you want to persist in the database

[[micronaut-listing-rest-resource-4]]
.Memory Method
[source,indent=0]
----
include::{workshop-github-raw}/micronaut-app/src/main/java/io/containerapps/javaruntime/workshop/micronaut/MicronautResource.java[tag=adocMethodMemory]
----

Let's also create a method to retrieve the statistics from the database.

[[micronaut-listing-rest-resource-5]]
.Method Returning all the Statistics
[source,indent=0]
----
include::{workshop-github-raw}/micronaut-app/src/main/java/io/containerapps/javaruntime/workshop/micronaut/MicronautResource.java[tag=adocMethodStats]
----

At this stage, the code does not compile yet, because there are a few missing classes.
Let's create them now.

== Transactions and ORM

When the database is enabled, the statistics are stored in the database.
For that we need a `Statistics` entity with a few enumerations that will be mapped to the Postgres database.
Create the `Statistics` entity in the `src/main/java/io/containerapps/javaruntime/workshop/micronaut` directory.

[[micronaut-listing-entity]]
.Statistics Entity
[source,indent=0]
----
include::{workshop-github-raw}/micronaut-app/src/main/java/io/containerapps/javaruntime/workshop/micronaut/Statistics.java[]
----

For manipulating the entity, we need a repository.
Create the `StatisticsRepository` class under the same package.

[[micronaut-listing-repository]]
.Statistics Repository
[source,indent=0]
----
include::{workshop-github-raw}/micronaut-app/src/main/java/io/containerapps/javaruntime/workshop/micronaut/StatisticsRepository.java[]
----

== Compiling the Application

You should have all the code to compile the application.
To make sure you have all the code and dependencies, run the following command:

[source,shell]
----
mvn compile
----

== Configuring the Application

We need to configure the default Postgres database and Hibernate ORM.
We also need this service to be exposed on the port 8702 (different port from the Quarkus application).
Add the following to the `src/main/resources/application.yml` file.

[[micronaut-listing-config]]
.Configuration Properties
[source,yaml,indent=0]
----
include::{workshop-github-raw}/micronaut-app/src/main/resources/application.yml[]
----

== Testing the Application Locally

Now, to make sure that the application works as expected, we need to write some tests.
Remember that the tests need a Postgres database to run.
For that, we need to configure TestContainers in a separate class (`MicronautApplicationTest`)
Create the `MicronautApplicationTest` class under the `src/test/java/io/containerapps/javaruntime/workshop/micronaut` package.

[[micronaut-listing-test]]
.Test Class Configuring TestContainers
[source,indent=0]
----
include::{workshop-github-raw}/micronaut-app/src/test/java/io/containerapps/javaruntime/workshop/micronaut/MicronautApplicationTest.java[]
----

Then, all our tests go into the `MicronautResourceTest` class.
Create the `MicronautResourceTest` class under the same package that `MicronautApplicationTest`.

[[micronaut-listing-test-1]]
.Header of the Test Class
[source,indent=0]
----
include::{workshop-github-raw}/micronaut-app/src/test/java/io/containerapps/javaruntime/workshop/micronaut/MicronautResourceTest.java[tag=adocHeader]
----

First, let's write a test to check that the `hello` method returns the right _Hello World_ string.

[[micronaut-listing-test-2]]
.Testing the Hello Endpoint
[source,indent=0]
----
include::{workshop-github-raw}/micronaut-app/src/test/java/io/containerapps/javaruntime/workshop/micronaut/MicronautResourceTest.java[tag=adocTestHello]
----

Then, we write another test to check that the `cpu` method consumes CPU and takes the right parameters.

[[micronaut-listing-test-3]]
.Testing the CPU Endpoint
[source,indent=0]
----
include::{workshop-github-raw}/micronaut-app/src/test/java/io/containerapps/javaruntime/workshop/micronaut/MicronautResourceTest.java[tag=adocTestCPU]
----

And we do the same for the `memory` method.

[[micronaut-listing-test-4]]
.Testing the Memory Endpoint
[source,indent=0]
----
include::{workshop-github-raw}/micronaut-app/src/test/java/io/containerapps/javaruntime/workshop/micronaut/MicronautResourceTest.java[tag=adocTestMemory]
----

Let's also create a simple test to make sure the statistics are stored in the database.

[[micronaut-listing-test-5]]
.Testing Retrieving the Statistics from the Database
[source,indent=0]
----
include::{workshop-github-raw}/micronaut-app/src/test/java/io/containerapps/javaruntime/workshop/micronaut/MicronautResourceTest.java[tag=adocTestStats]
----

Now that you have your tests methods, make sure you have Docker Desktop up and running (as it needs to start a Postgres database) and run them with the following command:

[source,shell]
----
mvn test
----

All the tests should pass and you should see the following output:

[source,shell]
----
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
----

== Running the Application Locally

Now that the tests are all green, let's execute the application locally and execute a few `curl` commands.
To run the application, we first need to have our Postgres database up and running.
Make sure you still have Docker up and running and execute under the `infrastructure` directory:

[source,shell]
----
docker compose -f postgres.yaml up
----

Under the `micronaut-app` directory, execute the following command:

[source,shell]
----
mvn mn:run
----

In another terminal you can execute the following `curl` commands to invoke the endpoint:

[source,shell]
----
curl 'localhost:8702/micronaut'

curl 'localhost:8702/micronaut/cpu?iterations=10&db=true&desc=java17'

curl 'localhost:8702/micronaut/memory?bites=10&db=true&desc=java17'
----

You can change the parameters to see how the application behaves.
Change the number of iterations and the number of bites to see how the performance is impacted (with and without database).

[source,shell]
----
curl 'localhost:8702/micronaut/cpu?iterations=50'
curl 'localhost:8702/micronaut/cpu?iterations=100'
curl 'localhost:8702/micronaut/cpu?iterations=100&db=true'

curl 'localhost:8702/micronaut/memory?bites=50'
curl 'localhost:8702/micronaut/memory?bites=100'
curl 'localhost:8702/micronaut/memory?bites=100&db=true'
----

You can check the content of the database with:

[source,shell]
----
curl 'localhost:8702/micronaut/stats' | jq
----

That's it for the Micronaut application.
We now have the Quarkus and Micronaut application fully tested, up and running, time to write the Spring Boot application.
