name: Build workshop docs and deploy to GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    name: Build and Deploy

    permissions:
      contents: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

    - name: Setup Node.js
      uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
      with:
        node-version: 18

    - name: Set up Java
      uses: actions/setup-java@e9fbacdec3bb3b6036605a3e6f7995d66773a8c6 # v3.14.2
      with:
        distribution: 'microsoft'
        java-version: '17'

    - name: Generate docs
      run: |
        cd docs
        shopt -s globstar
        npx -y cxa-track -t javascript-0000-yolasors **/*.adoc
        VERSION="sha.$(git rev-parse --short HEAD)"
        perl -i -pe "s/1.0.0-SNAPSHOT/$VERSION/g" pom.xml
        mvn generate-resources
        npx -y @moaw/cli@latest convert src/docs/asciidoc/index.adoc -a src/docs/asciidoc/attributes.json -d target/generated-docs/workshop.md

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/target/generated-docs/
