name: Build workshop docs and deploy to GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    name: Build and Deploy

    permissions:
      contents: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 18

    - name: Set up Java
      uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
      with:
        distribution: 'microsoft'
        java-version: '17'

    - name: Generate docs
      run: |
        cd docs
        shopt -s globstar
        npx -y cxa-track -t javascript-0000-yolasors **/*.adoc
        VERSION="sha.$(git rev-parse --short HEAD)"
        perl -i -pe "s/1.0.0-SNAPSHOT/$VERSION/g" pom.xml
        mvn generate-resources
        npx -y @moaw/cli@latest convert src/docs/asciidoc/index.adoc -a src/docs/asciidoc/attributes.json -d target/generated-docs/workshop.md

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/target/generated-docs/
